name: Snake
description: Snake
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.3.2
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/sfx/eat.wav
    - assets/sfx/game_over.wav
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  image_path: assets/icon/icon.png
  min_sdk_android: 21
